version: '3.9'

services:
  go_client:
    container_name: go_client
    build:
      context: .
      dockerfile: ./go_client/Dockerfile
    ports:
      - "8080:8080"

  python_server:
    container_name: python_server
    build:
      context: .
      dockerfile: ./python_server/Dockerfile
    ports:
      - "50051:50051"
